In [1]:
import pandas as pd
import numpy as nm

In [2]:
dataset=pd.read_csv("Placement.csv")
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           215 non-null    int64
 1   gender          215 non-null    object
 2   ssc_p           215 non-null    float64
 3   ssc_b           215 non-null    object
 4   hsc_p           215 non-null    float64
 5   hsc_b           215 non-null    object
 6   hsc_s           215 non-null    object
 7   degree_p        215 non-null    float64
 8   degree_t        215 non-null    object
 9   workex          215 non-null    object
 10  etest_p         215 non-null    float64
 11  specialisation  215 non-null    object
 12  mba_p           215 non-null    float64
 13  status          215 non-null    object
 14  salary          148 non-null    float64
dtypes: float64(6), int64(1), object(8)
memory usage: 25.3+ KB

In [4]:
dir(dataset)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_arith_method_with_reindex',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_create_data_for_split_and_tight_to_dict',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_nocopy',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'degree_p',
 'degree_t',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'etest_p',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'gender',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'hsc_b',
 'hsc_p',
 'hsc_s',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mba_p',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'salary',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sl_no',
 'sort_index',
 'sort_values',
 'specialisation',
 'squeeze',
 'ssc_b',
 'ssc_p',
 'stack',
 'status',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'workex',
 'xs']

In [5]:
dataset["degree_t"].dtype

dtype('O')

In [6]:
#Spliting quantitative and qualitative data
quan_columns=[] #to store quantitative data
qual_columns=[] #to store qualitative data
for columnName in dataset.columns:
    if(dataset[columnName].dtypes=='O'):
        qual_columns.append(columnName)
    else:
        quan_columns.append(columnName)
print("qual_columns:" ,qual_columns)
print("quan_columns:" ,quan_columns)

qual_columns: ['gender', 'ssc_b', 'hsc_b', 'hsc_s', 'degree_t', 'workex', 'specialisation', 'status']
quan_columns: ['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

In [7]:
#Measure of central tendency -Mean,Median,Mode  
#For quantitative data only able to identify the measures
dataset.describe()

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
count,215.000000,215.000000,215.000000,215.000000,215.000000,215.000000,148.000000
mean,108.000000,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
std,62.209324,10.827205,10.897509,7.358743,13.275956,5.833385,93457.452420
min,1.000000,40.890000,37.000000,50.000000,50.000000,51.210000,200000.000000
25%,54.500000,60.600000,60.900000,61.000000,60.000000,57.945000,240000.000000
50%,108.000000,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
75%,161.500000,75.700000,73.000000,72.000000,83.500000,66.255000,300000.000000
max,215.000000,89.400000,97.700000,91.000000,98.000000,77.890000,940000.000000

In [8]:
dataset_describe=pd.DataFrame(index=["MEAN","MEDIAN","MODE"],columns=quan_columns)
dataset_describe

       sl_no ssc_p hsc_p degree_p etest_p mba_p salary
MEAN     NaN   NaN   NaN      NaN     NaN   NaN    NaN
MEDIAN   NaN   NaN   NaN      NaN     NaN   NaN    NaN
MODE     NaN   NaN   NaN      NaN     NaN   NaN    NaN

In [9]:
for columnName in dataset_describe.columns:
    dataset_describe[columnName]["MEAN"]=dataset[columnName].mean()
    dataset_describe[columnName]["MEDIAN"]=dataset[columnName].median()
    dataset_describe[columnName]["MODE"]=dataset[columnName].mode()[0]
                            
dataset_describe

C:\Users\Sangeetha Viji\AppData\Local\Temp\ipykernel_19272\773245430.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset_describe[columnName]["MEAN"]=dataset[columnName].mean()
C:\Users\Sangeetha Viji\AppData\Local\Temp\ipykernel_19272\773245430.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset_describe[columnName]["MEDIAN"]=dataset[columnName].median()
C:\Users\Sangeetha Viji\AppData\Local\Temp\ipykernel_19272\773245430.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset_describe[columnName]["MODE"]=dataset[columnName].mode()[0]
C:\Users\Sangeetha Viji\AppData\Local\Temp\ipykernel_19272\773245430.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset_describe[columnName]["MEAN"]=dataset[columnName].mean()
C:\Users\Sangeetha Viji\AppData\Local\Temp\ipykernel_19272\773245430.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset_describe[columnName]["MEDIAN"]=dataset[columnName].median()
C:\Users\Sangeetha Viji\AppData\Local\Temp\ipykernel_19272\773245430.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset_describe[columnName]["MODE"]=dataset[columnName].mode()[0]
C:\Users\Sangeetha Viji\AppData\Local\Temp\ipykernel_19272\773245430.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset_describe[columnName]["MEAN"]=dataset[columnName].mean()
C:\Users\Sangeetha Viji\AppData\Local\Temp\ipykernel_19272\773245430.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset_describe[columnName]["MEDIAN"]=dataset[columnName].median()
C:\Users\Sangeetha Viji\AppData\Local\Temp\ipykernel_19272\773245430.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset_describe[columnName]["MODE"]=dataset[columnName].mode()[0]
C:\Users\Sangeetha Viji\AppData\Local\Temp\ipykernel_19272\773245430.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset_describe[columnName]["MEAN"]=dataset[columnName].mean()
C:\Users\Sangeetha Viji\AppData\Local\Temp\ipykernel_19272\773245430.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset_describe[columnName]["MEDIAN"]=dataset[columnName].median()
C:\Users\Sangeetha Viji\AppData\Local\Temp\ipykernel_19272\773245430.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset_describe[columnName]["MODE"]=dataset[columnName].mode()[0]
C:\Users\Sangeetha Viji\AppData\Local\Temp\ipykernel_19272\773245430.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset_describe[columnName]["MEAN"]=dataset[columnName].mean()
C:\Users\Sangeetha Viji\AppData\Local\Temp\ipykernel_19272\773245430.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset_describe[columnName]["MEDIAN"]=dataset[columnName].median()
C:\Users\Sangeetha Viji\AppData\Local\Temp\ipykernel_19272\773245430.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset_describe[columnName]["MODE"]=dataset[columnName].mode()[0]
C:\Users\Sangeetha Viji\AppData\Local\Temp\ipykernel_19272\773245430.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset_describe[columnName]["MEAN"]=dataset[columnName].mean()
C:\Users\Sangeetha Viji\AppData\Local\Temp\ipykernel_19272\773245430.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset_describe[columnName]["MEDIAN"]=dataset[columnName].median()
C:\Users\Sangeetha Viji\AppData\Local\Temp\ipykernel_19272\773245430.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset_describe[columnName]["MODE"]=dataset[columnName].mode()[0]
C:\Users\Sangeetha Viji\AppData\Local\Temp\ipykernel_19272\773245430.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset_describe[columnName]["MEAN"]=dataset[columnName].mean()
C:\Users\Sangeetha Viji\AppData\Local\Temp\ipykernel_19272\773245430.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset_describe[columnName]["MEDIAN"]=dataset[columnName].median()
C:\Users\Sangeetha Viji\AppData\Local\Temp\ipykernel_19272\773245430.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset_describe[columnName]["MODE"]=dataset[columnName].mode()[0]

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
MEAN,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
MEDIAN,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
MODE,1,62.0,63.0,65.0,60.0,56.7,300000.0

In [10]:
#To identify location of data

dataset_describe=pd.DataFrame(index=["MEAN","MEDIAN","MODE","Q1","Q1:25%","Q2:50%","Q3:75%","Q4:100%","IQR","1.5Rule","Lesser_Outlier_Range","Greater_Outlier_Range","Min","Max"],columns=quan_columns)
for columnName in dataset_describe.columns:
    dataset_describe.loc["MEAN",columnName]=dataset[columnName].mean()
    dataset_describe.loc["MEDIAN",columnName]=dataset[columnName].median()
    dataset_describe.loc["MODE",columnName]=dataset[columnName].mode()[0]
    dataset_describe.loc["Q1",columnName]=nm.percentile(dataset[columnName],25)  #Because salary having null values, NAN coming for salary
    dataset_describe.loc["Q1:25%",columnName]=dataset.describe()[columnName]["25%"]
    dataset_describe.loc["Q2:50%",columnName]=dataset.describe()[columnName]["50%"]
    dataset_describe.loc["Q3:75%",columnName]=dataset.describe()[columnName]["75%"]
    dataset_describe.loc["Q4:100%",columnName]=dataset.describe()[columnName]["max"]
    dataset_describe.loc["IQR",columnName]= dataset_describe.loc["Q3:75%",columnName]-dataset_describe.loc["Q1:25%",columnName]
    dataset_describe.loc["1.5Rule",columnName]=1.5*dataset_describe.loc["IQR",columnName]
    dataset_describe.loc["Lesser_Outlier_Range",columnName]=dataset_describe.loc["Q1:25%",columnName]-dataset_describe.loc["1.5Rule",columnName]
    dataset_describe.loc["Greater_Outlier_Range",columnName]=dataset_describe.loc["Q3:75%",columnName]+dataset_describe.loc["1.5Rule",columnName]
    dataset_describe.loc["Min",columnName]=dataset[columnName].min()
    dataset_describe.loc["Max",columnName]=dataset[columnName].max()
    
   
                            
dataset_describe

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
MEAN,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
MEDIAN,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
MODE,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1,54.5,60.6,60.9,61.0,60.0,57.945,NaN
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
Q4:100%,215.0,89.4,97.7,91.0,98.0,77.89,940000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5Rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
Lesser_Outlier_Range,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
Greater_Outlier_Range,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Min,1,40.89,37.0,50.0,50.0,51.21,200000.0
Max,215,89.4,97.7,91.0,98.0,77.89,940000.0

In [11]:
lesser_outlier=[]
greater_outlier=[]
for columnName in quan_columns:
    if(dataset_describe[columnName]["Min"]<dataset_describe[columnName]["Lesser_Outlier_Range"]):
        lesser_outlier.append(columnName)
    if(dataset_describe[columnName]["Max"]>dataset_describe[columnName]["Greater_Outlier_Range"]):
        greater_outlier.append(columnName)
print("lesser_outlier_columns:",lesser_outlier)
print("greater_outlier_columns:",greater_outlier)

lesser_outlier_columns: ['hsc_p']
greater_outlier_columns: ['hsc_p', 'degree_p', 'salary']

In [12]:
#replacing the outlier with the defined range
for columnName in lesser_outlier:
    dataset.loc[
        dataset[columnName] < dataset_describe.loc["Lesser_Outlier_Range", columnName],
        columnName
    ] = dataset_describe.loc["Lesser_Outlier_Range", columnName]


for columnName in greater_outlier:
    dataset.loc[
        dataset[columnName] > dataset_describe.loc["Greater_Outlier_Range", columnName],
        columnName
    ] = dataset_describe.loc["Greater_Outlier_Range", columnName]

In [13]:
dataset["hsc_p"].value_counts()

hsc_p
63.00    14
62.00    12
67.00     9
60.00     9
70.00     8
         ..
65.50     1
77.60     1
70.20     1
61.40     1
61.33     1
Name: count, Length: 91, dtype: int64

In [14]:
dataset["hsc_p"].value_counts().index

Index([ 63.0,  62.0,  67.0,  60.0,  70.0,  64.0,  65.0,  61.0,  73.0, 42.75,
        68.0,  47.0,  78.0,  51.0,  58.0,  76.0,  79.0,  75.0,  57.0,  74.0,
        82.0,  80.0,  59.0,  72.0, 91.15,  55.0,  66.0,  62.5,  90.0,  50.0,
        56.0,  53.0,  77.0,  73.4,  64.8,  68.4,  87.0,  52.0, 78.33,  91.0,
        49.2,  73.6,  49.8,  73.5,  76.5,  54.6,  60.8,  66.2, 45.83,  66.6,
       65.58, 83.83, 70.29, 61.12,  73.2, 71.98,  81.0,  44.0, 63.16, 89.83,
        90.9,  70.4,  71.4,  64.2,  78.5,  69.0,  54.0,  66.8,  72.8,  71.0,
        89.7, 64.89, 65.66,  86.0, 58.66,  60.5, 74.66,  69.4,  49.0,  87.6,
        72.5,  67.2, 50.83,  71.5, 60.33, 62.83,  65.5,  77.6,  70.2,  61.4,
       61.33],
      dtype='float64', name='hsc_p')

In [15]:
dataset["hsc_p"].value_counts().values

array([14, 12,  9,  9,  8,  8,  6,  6,  6,  5,  4,  4,  4,  4,  4,  4,  4,
        3,  3,  3,  3,  3,  3,  3,  3,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1])

In [16]:
#To identify location of data

dataset_describe=pd.DataFrame(index=["MEAN","MEDIAN","MODE","Q1","Q1:25%","Q2:50%","Q3:75%","Q4:100%","IQR","1.5Rule","Lesser_Outlier_Range","Greater_Outlier_Range","Min","Max"],columns=quan_columns)
for columnName in dataset_describe.columns:
    dataset_describe.loc["MEAN",columnName]=dataset[columnName].mean()
    dataset_describe.loc["MEDIAN",columnName]=dataset[columnName].median()
    dataset_describe.loc["MODE",columnName]=dataset[columnName].mode()[0]
    dataset_describe.loc["Q1",columnName]=nm.percentile(dataset[columnName],25)  #Because salary having null values, NAN coming for salary
    dataset_describe.loc["Q1:25%",columnName]=dataset.describe()[columnName]["25%"]
    dataset_describe.loc["Q2:50%",columnName]=dataset.describe()[columnName]["50%"]
    dataset_describe.loc["Q3:75%",columnName]=dataset.describe()[columnName]["75%"]
    dataset_describe.loc["Q4:100%",columnName]=dataset.describe()[columnName]["max"]
    dataset_describe.loc["IQR",columnName]= dataset_describe.loc["Q3:75%",columnName]-dataset_describe.loc["Q1:25%",columnName]
    dataset_describe.loc["1.5Rule",columnName]=1.5*dataset_describe.loc["IQR",columnName]
    dataset_describe.loc["Lesser_Outlier_Range",columnName]=dataset_describe.loc["Q1:25%",columnName]-dataset_describe.loc["1.5Rule",columnName]
    dataset_describe.loc["Greater_Outlier_Range",columnName]=dataset_describe.loc["Q3:75%",columnName]+dataset_describe.loc["1.5Rule",columnName]
    dataset_describe.loc["Min",columnName]=dataset[columnName].min()
    dataset_describe.loc["Max",columnName]=dataset[columnName].max()
   
                            
dataset_describe

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
MEAN,108.0,67.303395,66.334744,66.358558,72.100558,62.278186,277648.648649
MEDIAN,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
MODE,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1,54.5,60.6,60.9,61.0,60.0,57.945,NaN
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
Q4:100%,215.0,89.4,91.15,88.5,98.0,77.89,390000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5Rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
Lesser_Outlier_Range,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
Greater_Outlier_Range,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Min,1,40.89,42.75,50.0,50.0,51.21,200000.0
Max,215,89.4,91.15,88.5,98.0,77.89,390000.0

In [17]:
n=len(dataset)

In [18]:
freqTable=pd.DataFrame(columns=["Unique_values","Frequency","Relative_frequency","Cumsum"])
freqTable

Empty DataFrame
Columns: [Unique_values, Frequency, Relative_frequency, Cumsum]
Index: []

In [19]:
dataset[quan_columns]

     sl_no  ssc_p  hsc_p  degree_p  etest_p  mba_p    salary
0        1  67.00  91.00     58.00     55.0  58.80  270000.0
1        2  79.33  78.33     77.48     86.5  66.28  200000.0
2        3  65.00  68.00     64.00     75.0  57.80  250000.0
3        4  56.00  52.00     52.00     66.0  59.43       NaN
4        5  85.80  73.60     73.30     96.8  55.50  390000.0
..     ...    ...    ...       ...      ...    ...       ...
210    211  80.60  82.00     77.60     91.0  74.49  390000.0
211    212  58.00  60.00     72.00     74.0  53.62  275000.0
212    213  67.00  67.00     73.00     59.0  69.72  295000.0
213    214  74.00  66.00     58.00     70.0  60.23  204000.0
214    215  62.00  58.00     53.00     89.0  60.22       NaN

[215 rows x 7 columns]

In [25]:
for columnName in dataset[quan_columns]:
    freqTable=pd.DataFrame(columns=["Unique_values","Frequency","Relative_frequency","Cumsum"])
    print(columnName)
    freqTable["Unique_values"]=dataset[columnName].value_counts().index
    freqTable["Frequency"]=dataset[columnName].value_counts().values
    freqTable["Relative_frequency"]=dataset[columnName].value_counts().values/n
    freqTable["Cumsum"]=freqTable["Relative_frequency"].cumsum()
    print(freqTable)

sl_no
     Unique_values  Frequency  Relative_frequency    Cumsum
0                1          1            0.004651  0.004651
1                2          1            0.004651  0.009302
2                3          1            0.004651  0.013953
3                4          1            0.004651  0.018605
4                5          1            0.004651  0.023256
..             ...        ...                 ...       ...
210            211          1            0.004651  0.981395
211            212          1            0.004651  0.986047
212            213          1            0.004651  0.990698
213            214          1            0.004651  0.995349
214            215          1            0.004651  1.000000

[215 rows x 4 columns]
ssc_p
     Unique_values  Frequency  Relative_frequency    Cumsum
0            62.00         11            0.051163  0.051163
1            63.00         10            0.046512  0.097674
2            67.00          9            0.041860  0.139535
3            73.00          9            0.041860  0.181395
4            52.00          9            0.041860  0.223256
..             ...        ...                 ...       ...
98           55.68          1            0.004651  0.981395
99           41.00          1            0.004651  0.986047
100          83.33          1            0.004651  0.990698
101          43.00          1            0.004651  0.995349
102          80.60          1            0.004651  1.000000

[103 rows x 4 columns]
hsc_p
    Unique_values  Frequency  Relative_frequency    Cumsum
0           63.00         14            0.065116  0.065116
1           62.00         12            0.055814  0.120930
2           67.00          9            0.041860  0.162791
3           60.00          9            0.041860  0.204651
4           70.00          8            0.037209  0.241860
..            ...        ...                 ...       ...
86          65.50          1            0.004651  0.981395
87          77.60          1            0.004651  0.986047
88          70.20          1            0.004651  0.990698
89          61.40          1            0.004651  0.995349
90          61.33          1            0.004651  1.000000

[91 rows x 4 columns]
degree_p
    Unique_values  Frequency  Relative_frequency    Cumsum
0           65.00         20            0.093023  0.093023
1           66.00         13            0.060465  0.153488
2           72.00         12            0.055814  0.209302
3           64.00         11            0.051163  0.260465
4           58.00          9            0.041860  0.302326
..            ...        ...                 ...       ...
84          64.80          1            0.004651  0.981395
85          56.30          1            0.004651  0.986047
86          88.50          1            0.004651  0.990698
87          56.87          1            0.004651  0.995349
88          77.60          1            0.004651  1.000000

[89 rows x 4 columns]
etest_p
    Unique_values  Frequency  Relative_frequency    Cumsum
0           60.00         14            0.065116  0.065116
1           80.00          8            0.037209  0.102326
2           67.00          7            0.032558  0.134884
3           75.00          7            0.032558  0.167442
4           89.00          6            0.027907  0.195349
..            ...        ...                 ...       ...
95          87.55          1            0.004651  0.981395
96          61.28          1            0.004651  0.986047
97          88.56          1            0.004651  0.990698
98          92.66          1            0.004651  0.995349
99          91.00          1            0.004651  1.000000

[100 rows x 4 columns]
mba_p
     Unique_values  Frequency  Relative_frequency    Cumsum
0            56.70          3            0.013953  0.013953
1            62.48          2            0.009302  0.023256
2            64.15          2            0.009302  0.032558
3            64.08          2            0.009302  0.041860
4            61.29          2            0.009302  0.051163
..             ...        ...                 ...       ...
200          74.49          1            0.004651  0.981395
201          53.62          1            0.004651  0.986047
202          69.72          1            0.004651  0.990698
203          60.23          1            0.004651  0.995349
204          60.22          1            0.004651  1.000000

[205 rows x 4 columns]
salary
    Unique_values  Frequency  Relative_frequency    Cumsum
0        300000.0         22            0.102326  0.102326
1        250000.0         18            0.083721  0.186047
2        240000.0         15            0.069767  0.255814
3        390000.0         15            0.069767  0.325581
4        260000.0          7            0.032558  0.358140
5        200000.0          6            0.027907  0.386047
6        360000.0          6            0.027907  0.413953
7        265000.0          6            0.027907  0.441860
8        275000.0          5            0.023256  0.465116
9        220000.0          5            0.023256  0.488372
10       270000.0          4            0.018605  0.506977
11       210000.0          4            0.018605  0.525581
12       350000.0          3            0.013953  0.539535
13       216000.0          3            0.013953  0.553488
14       204000.0          2            0.009302  0.562791
15       236000.0          2            0.009302  0.572093
16       230000.0          2            0.009302  0.581395
17       280000.0          2            0.009302  0.590698
18       218000.0          2            0.009302  0.600000
19       252000.0          2            0.009302  0.609302
20       276000.0          2            0.009302  0.618605
21       320000.0          1            0.004651  0.623256
22       278000.0          1            0.004651  0.627907
23       231000.0          1            0.004651  0.632558
24       287000.0          1            0.004651  0.637209
25       268000.0          1            0.004651  0.641860
26       336000.0          1            0.004651  0.646512
27       380000.0          1            0.004651  0.651163
28       225000.0          1            0.004651  0.655814
29       233000.0          1            0.004651  0.660465
30       340000.0          1            0.004651  0.665116
31       255000.0          1            0.004651  0.669767
32       285000.0          1            0.004651  0.674419
33       290000.0          1            0.004651  0.679070
34       264000.0          1            0.004651  0.683721
35       295000.0          1            0.004651  0.688372

In [22]:

dataset_describe=pd.DataFrame(index=["MEAN","MEDIAN","MODE","Q1","Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%","IQR","1.5Rule","Lesser_Outlier_Range","Greater_Outlier_Range","Min","Max","skew","kurtosis"],columns=quan_columns)
for columnName in dataset_describe.columns:
    dataset_describe.loc["MEAN",columnName]=dataset[columnName].mean()
    dataset_describe.loc["MEDIAN",columnName]=dataset[columnName].median()
    dataset_describe.loc["MODE",columnName]=dataset[columnName].mode()[0]
    dataset_describe.loc["Q1",columnName]=nm.percentile(dataset[columnName],25)  #Because salary having null values, NAN coming for salary
    dataset_describe.loc["Q1:25%",columnName]=dataset.describe()[columnName]["25%"]
    dataset_describe.loc["Q2:50%",columnName]=dataset.describe()[columnName]["50%"]
    dataset_describe.loc["Q3:75%",columnName]=dataset.describe()[columnName]["75%"]
    dataset_describe.loc["99%",columnName]=nm.percentile(dataset[columnName],99)  #Because salary having null values, NAN coming for salary
    dataset_describe.loc["Q4:100%",columnName]=dataset.describe()[columnName]["max"]
    dataset_describe.loc["IQR",columnName]= dataset_describe.loc["Q3:75%",columnName]-dataset_describe.loc["Q1:25%",columnName]
    dataset_describe.loc["1.5Rule",columnName]=1.5*dataset_describe.loc["IQR",columnName]
    dataset_describe.loc["Lesser_Outlier_Range",columnName]=dataset_describe.loc["Q1:25%",columnName]-dataset_describe.loc["1.5Rule",columnName]
    dataset_describe.loc["Greater_Outlier_Range",columnName]=dataset_describe.loc["Q3:75%",columnName]+dataset_describe.loc["1.5Rule",columnName]
    dataset_describe.loc["Min",columnName]=dataset[columnName].min()
    dataset_describe.loc["Max",columnName]=dataset[columnName].max()
    dataset_describe.loc["skew",columnName]=dataset[columnName].skew()
    dataset_describe.loc["kurtosis",columnName]=dataset[columnName].kurtosis()
   
                            
dataset_describe

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
MEAN,108.0,67.303395,66.334744,66.358558,72.100558,62.278186,277648.648649
MEDIAN,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
MODE,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1,54.5,60.6,60.9,61.0,60.0,57.945,NaN
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
99%,212.86,87.0,91.129,83.86,97.0,76.1142,NaN
Q4:100%,215.0,89.4,91.15,88.5,98.0,77.89,390000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5Rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
Lesser_Outlier_Range,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
Greater_Outlier_Range,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Min,1,40.89,42.75,50.0,50.0,51.21,200000.0
Max,215,89.4,91.15,88.5,98.0,77.89,390000.0
skew,0.0,-0.132649,0.162611,0.204164,0.282308,0.313576,0.8067
kurtosis,-1.2,-0.60751,0.086901,-0.09749,-1.08858,-0.470723,-0.239837

In [26]:
1
dataset_describe=pd.DataFrame(index=["MEAN","MEDIAN","MODE","Q1","Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%","IQR","1.5Rule","Lesser_Outlier_Range","Greater_Outlier_Range","Min","Max","skew","kurtosis","Var","Std_Deviation"],columns=quan_columns)
for columnName in dataset_describe.columns:
    dataset_describe.loc["MEAN",columnName]=dataset[columnName].mean()
    dataset_describe.loc["MEDIAN",columnName]=dataset[columnName].median()
    dataset_describe.loc["MODE",columnName]=dataset[columnName].mode()[0]
    dataset_describe.loc["Q1",columnName]=nm.percentile(dataset[columnName],25)  #Because salary having null values, NAN coming for salary
    dataset_describe.loc["Q1:25%",columnName]=dataset.describe()[columnName]["25%"]
    dataset_describe.loc["Q2:50%",columnName]=dataset.describe()[columnName]["50%"]
    dataset_describe.loc["Q3:75%",columnName]=dataset.describe()[columnName]["75%"]
    dataset_describe.loc["99%",columnName]=nm.percentile(dataset[columnName],99)  #Because salary having null values, NAN coming for salary
    dataset_describe.loc["Q4:100%",columnName]=dataset.describe()[columnName]["max"]
    dataset_describe.loc["IQR",columnName]= dataset_describe.loc["Q3:75%",columnName]-dataset_describe.loc["Q1:25%",columnName]
    dataset_describe.loc["1.5Rule",columnName]=1.5*dataset_describe.loc["IQR",columnName]
    dataset_describe.loc["Lesser_Outlier_Range",columnName]=dataset_describe.loc["Q1:25%",columnName]-dataset_describe.loc["1.5Rule",columnName]
    dataset_describe.loc["Greater_Outlier_Range",columnName]=dataset_describe.loc["Q3:75%",columnName]+dataset_describe.loc["1.5Rule",columnName]
    dataset_describe.loc["Min",columnName]=dataset[columnName].min()
    dataset_describe.loc["Max",columnName]=dataset[columnName].max()
    dataset_describe.loc["skew",columnName]=dataset[columnName].skew()
    dataset_describe.loc["kurtosis",columnName]=dataset[columnName].kurtosis() 
    dataset_describe.loc["Var",columnName]=dataset[columnName].var()
    dataset_describe.loc["Std_Deviation",columnName]=dataset[columnName].std()
   
   
                            
dataset_describe

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
MEAN,108.0,67.303395,66.334744,66.358558,72.100558,62.278186,277648.648649
MEDIAN,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
MODE,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1,54.5,60.6,60.9,61.0,60.0,57.945,NaN
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
99%,212.86,87.0,91.129,83.86,97.0,76.1142,NaN
Q4:100%,215.0,89.4,91.15,88.5,98.0,77.89,390000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5Rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
Lesser_Outlier_Range,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
Greater_Outlier_Range,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Min,1,40.89,42.75,50.0,50.0,51.21,200000.0
Max,215,89.4,91.15,88.5,98.0,77.89,390000.0
skew,0.0,-0.132649,0.162611,0.204164,0.282308,0.313576,0.8067
kurtosis,-1.2,-0.60751,0.086901,-0.09749,-1.08858,-0.470723,-0.239837
Var,3870.0,117.228377,112.063731,53.60471,176.251018,34.028376,2944596800.882515
Std_Deviation,62.209324,10.827205,10.586016,7.321524,13.275956,5.833385,54264.139179