In [1]:
import pandas as pd
import numpy as nm

In [2]:
dataset=pd.read_csv("Placement.csv")
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [3]:
from DSunivariateclass import univariate
quan_columns,qual_columns=univariate.quan_qual(dataset)
print(quan_columns)
print(qual_columns)

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']
['gender', 'ssc_b', 'hsc_b', 'hsc_s', 'degree_t', 'workex', 'specialisation', 'status']

In [4]:
dataset_describe=univariate.datasetdescribe(dataset,quan_columns)
dataset_describe

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
MEAN,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
MEDIAN,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
MODE,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1,54.5,60.6,60.9,61.0,60.0,57.945,NaN
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
Q4:100%,215.0,89.4,97.7,91.0,98.0,77.89,940000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5Rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
Lesser_Outlier_Range,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
Greater_Outlier_Range,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Min,1,40.89,37.0,50.0,50.0,51.21,200000.0
Max,215,89.4,97.7,91.0,98.0,77.89,940000.0
skew,0.0,-0.132649,0.163639,0.244917,0.282308,0.313576,3.569747
kurtosis,-1.2,-0.60751,0.450765,0.052143,-1.08858,-0.470723,18.544273
Var,3870.0,117.228377,118.755706,54.151103,176.251018,34.028376,8734295412.759695
Std_Deviation,62.209324,10.827205,10.897509,7.358743,13.275956,5.833385,93457.45242

In [5]:
#identify the outlier
lesser_outlier,greater_outlier=univariate.identifyoutlier(dataset_describe,quan_columns)
print("lesser_outlier_columns:",lesser_outlier)
print("greater_outlier_columns:",greater_outlier)

lesser_outlier_columns: ['hsc_p']
greater_outlier_columns: ['hsc_p', 'degree_p', 'salary']

In [6]:
#replacing the outlier with the defined range
univariate.replaceoutlier(dataset,dataset_describe,lesser_outlier,greater_outlier)

In [7]:
dataset_describe=univariate.datasetdescribe(dataset,quan_columns)
dataset_describe

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
MEAN,108.0,67.303395,66.334744,66.358558,72.100558,62.278186,277648.648649
MEDIAN,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
MODE,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1,54.5,60.6,60.9,61.0,60.0,57.945,NaN
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
Q4:100%,215.0,89.4,91.15,88.5,98.0,77.89,390000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5Rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
Lesser_Outlier_Range,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
Greater_Outlier_Range,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Min,1,40.89,42.75,50.0,50.0,51.21,200000.0
Max,215,89.4,91.15,88.5,98.0,77.89,390000.0
skew,0.0,-0.132649,0.162611,0.204164,0.282308,0.313576,0.8067
kurtosis,-1.2,-0.60751,0.086901,-0.09749,-1.08858,-0.470723,-0.239837
Var,3870.0,117.228377,112.063731,53.60471,176.251018,34.028376,2944596800.882515
Std_Deviation,62.209324,10.827205,10.586016,7.321524,13.275956,5.833385,54264.139179

In [8]:
univariate.freqtable(dataset,quan_columns)

sl_no
     Unique_values  Frequency  Relative_frequency  Cumsum
0                1          1                   1       1
1                2          1                   1       2
2                3          1                   1       3
3                4          1                   1       4
4                5          1                   1       5
..             ...        ...                 ...     ...
210            211          1                   1     211
211            212          1                   1     212
212            213          1                   1     213
213            214          1                   1     214
214            215          1                   1     215

[215 rows x 4 columns]
ssc_p
     Unique_values  Frequency  Relative_frequency  Cumsum
0            62.00         11                  11      11
1            63.00         10                  10      21
2            67.00          9                   9      30
3            73.00          9                   9      39
4            52.00          9                   9      48
..             ...        ...                 ...     ...
98           55.68          1                   1     211
99           41.00          1                   1     212
100          83.33          1                   1     213
101          43.00          1                   1     214
102          80.60          1                   1     215

[103 rows x 4 columns]
hsc_p
    Unique_values  Frequency  Relative_frequency  Cumsum
0           63.00         14                  14      14
1           62.00         12                  12      26
2           67.00          9                   9      35
3           60.00          9                   9      44
4           70.00          8                   8      52
..            ...        ...                 ...     ...
86          65.50          1                   1     211
87          77.60          1                   1     212
88          70.20          1                   1     213
89          61.40          1                   1     214
90          61.33          1                   1     215

[91 rows x 4 columns]
degree_p
    Unique_values  Frequency  Relative_frequency  Cumsum
0           65.00         20                  20      20
1           66.00         13                  13      33
2           72.00         12                  12      45
3           64.00         11                  11      56
4           58.00          9                   9      65
..            ...        ...                 ...     ...
84          64.80          1                   1     211
85          56.30          1                   1     212
86          88.50          1                   1     213
87          56.87          1                   1     214
88          77.60          1                   1     215

[89 rows x 4 columns]
etest_p
    Unique_values  Frequency  Relative_frequency  Cumsum
0           60.00         14                  14      14
1           80.00          8                   8      22
2           67.00          7                   7      29
3           75.00          7                   7      36
4           89.00          6                   6      42
..            ...        ...                 ...     ...
95          87.55          1                   1     211
96          61.28          1                   1     212
97          88.56          1                   1     213
98          92.66          1                   1     214
99          91.00          1                   1     215

[100 rows x 4 columns]
mba_p
     Unique_values  Frequency  Relative_frequency  Cumsum
0            56.70          3                   3       3
1            62.48          2                   2       5
2            64.15          2                   2       7
3            64.08          2                   2       9
4            61.29          2                   2      11
..             ...        ...                 ...     ...
200          74.49          1                   1     211
201          53.62          1                   1     212
202          69.72          1                   1     213
203          60.23          1                   1     214
204          60.22          1                   1     215

[205 rows x 4 columns]
salary
    Unique_values  Frequency  Relative_frequency  Cumsum
0        300000.0         22                  22      22
1        250000.0         18                  18      40
2        240000.0         15                  15      55
3        390000.0         15                  15      70
4        260000.0          7                   7      77
5        200000.0          6                   6      83
6        360000.0          6                   6      89
7        265000.0          6                   6      95
8        275000.0          5                   5     100
9        220000.0          5                   5     105
10       270000.0          4                   4     109
11       210000.0          4                   4     113
12       350000.0          3                   3     116
13       216000.0          3                   3     119
14       204000.0          2                   2     121
15       236000.0          2                   2     123
16       230000.0          2                   2     125
17       280000.0          2                   2     127
18       218000.0          2                   2     129
19       252000.0          2                   2     131
20       276000.0          2                   2     133
21       320000.0          1                   1     134
22       278000.0          1                   1     135
23       231000.0          1                   1     136
24       287000.0          1                   1     137
25       268000.0          1                   1     138
26       336000.0          1                   1     139
27       380000.0          1                   1     140
28       225000.0          1                   1     141
29       233000.0          1                   1     142
30       340000.0          1                   1     143
31       255000.0          1                   1     144
32       285000.0          1                   1     145
33       290000.0          1                   1     146
34       264000.0          1                   1     147
35       295000.0          1                   1     148