In [1]:
import pandas as pd
import numpy as nm

In [7]:
dataset=pd.read_csv("uk_universities.csv")
dataset

,University_name,Region,Founded_year,Motto,UK_rank,World_rank,CWUR_score,Minimum_IELTS_score,UG_average_fees_(in_pounds),PG_average_fees_(in_pounds),...,Student_satisfaction,Student_enrollment,Academic_staff,Control_type,Academic_Calender,Campus_setting,Estimated_cost_of_living_per_year_(in_pounds),Latitude,Longitude,Website
0,University of Cambridge,East of England,1209,"From here, light and sacred draughts",1,4,94.1,6.5,21750,23187,...,85.50%,"20,000-24,999","over-5,000",Public,Trimesters,Urban,12000,52.2054,0.1132,www.cam.ac.uk
1,University of Oxford,South East England,1096,The Lord is my light,2,2,93.3,6.5,21770,19888,...,86.50%,"25,000-29,999","over-5,000",Public,Trimesters,Urban,11500,51.7548,-1.2544,www.ox.ac.uk
2,University of St Andrews,Scotland,1413,Ever to excel,3,86,75.8,6.5,17040,15440,...,87.90%,"10,000-14,999","1,000-1,499",Public,Semesters,Suburban,12000,56.3417,-2.7943,www.st-andrews.ac.uk
3,Imperial College London,London,1907,Knowledge is the adornment and safeguard of th...,4,8,86.6,6.5,23500,29900,...,77.90%,"15,000-19,999","4,000-4,499",Public,Continuous,Urban,10700,51.4988,-0.1749,www.ic.ac.uk
4,Loughborough University,East Midlands,1966,"With Truth, Knowledge and Labour",5,404,72.8,5.5,16400,16400,...,85.80%,"15,000-19,999","1,500-1,999",Public,Semesters,Suburban,9398,52.7650,-1.2321,www.lboro.ac.uk/
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,University of East London,London,1992,Science and fulfillment of vows,127,971,NaN,4.5,10700,11700,...,76.10%,"10,000-14,999",900-999,Public,Semesters,Suburban,10229,51.5076,0.0651,www.uel.ac.uk
127,University of Bedfordshire,East of England,2006,NaN,128,1281,NaN,4.5,9750,9900,...,77.40%,"10,000-14,999",500-599,Public,Semesters,Urban,9415,51.8779,-0.4093,www.beds.ac.uk
128,University of Suffolk,East of England,2007,Honesty and diligence,129,4030,NaN,4.5,9495,9495,...,76.00%,"7,000-7,999",200-299,Public,NaN,NaN,9415,52.0523,1.1629,www.ucs.ac.uk/
129,Wrexham Glyndwr University,Wales,2008,Confidence through Education,130,2397,NaN,4.5,10250,10500,...,74.30%,"5,000-5,999",200-299,Public,NaN,Urban,7771,53.0526,-3.0062,www.glyndwr.ac.uk/
130,Ravensbourne University London,London,1962,Designed for industry,131,2759,NaN,5.5,9250,9250,...,66.10%,"2,000-2,999",100-199,Public,Semesters,Urban,10229,51.5017,0.0055,www.ravensbourne.ac.uk

In [8]:
from DSunivariateclass import univariate
quan_columns,qual_columns=univariate.quan_qual(dataset)
print("quan_columns:", quan_columns)
print("qual_columns:", qual_columns)

quan_columns: ['Founded_year', 'UK_rank', 'World_rank', 'CWUR_score', 'Minimum_IELTS_score', 'UG_average_fees_(in_pounds)', 'PG_average_fees_(in_pounds)', 'Estimated_cost_of_living_per_year_(in_pounds)', 'Latitude', 'Longitude']
qual_columns: ['University_name', 'Region', 'Motto', 'International_students', 'Student_satisfaction', 'Student_enrollment', 'Academic_staff', 'Control_type', 'Academic_Calender', 'Campus_setting', 'Website']

In [9]:
print(dataset.isnull().sum())

University_name                                   0
Region                                            0
Founded_year                                      0
Motto                                            17
UK_rank                                           0
World_rank                                        0
CWUR_score                                       47
Minimum_IELTS_score                               0
UG_average_fees_(in_pounds)                       0
PG_average_fees_(in_pounds)                       0
International_students                            0
Student_satisfaction                              0
Student_enrollment                                0
Academic_staff                                    0
Control_type                                      0
Academic_Calender                                26
Campus_setting                                   18
Estimated_cost_of_living_per_year_(in_pounds)     0
Latitude                                          0
Longitude                                         0
Website                                           0
dtype: int64

In [10]:
from sklearn.impute import SimpleImputer
imp=SimpleImputer(missing_values=nm.nan,strategy='mean')
imp.fit(dataset[quan_columns])
df=imp.transform(dataset[quan_columns])
df

array([[ 1.20900e+03,  1.00000e+00,  4.00000e+00, ...,  1.20000e+04,
         5.22054e+01,  1.13200e-01],
       [ 1.09600e+03,  2.00000e+00,  2.00000e+00, ...,  1.15000e+04,
         5.17548e+01, -1.25440e+00],
       [ 1.41300e+03,  3.00000e+00,  8.60000e+01, ...,  1.20000e+04,
         5.63417e+01, -2.79430e+00],
       ...,
       [ 2.00700e+03,  1.29000e+02,  4.03000e+03, ...,  9.41500e+03,
         5.20523e+01,  1.16290e+00],
       [ 2.00800e+03,  1.30000e+02,  2.39700e+03, ...,  7.77100e+03,
         5.30526e+01, -3.00620e+00],
       [ 1.96200e+03,  1.31000e+02,  2.75900e+03, ...,  1.02290e+04,
         5.15017e+01,  5.50000e-03]], shape=(131, 10))

In [11]:
df=pd.DataFrame(df,columns=quan_columns)

In [12]:
df

,Founded_year,UK_rank,World_rank,CWUR_score,Minimum_IELTS_score,UG_average_fees_(in_pounds),PG_average_fees_(in_pounds),Estimated_cost_of_living_per_year_(in_pounds),Latitude,Longitude
0,1209.0,1.0,4.0,94.100000,6.5,21750.0,23187.0,12000.0,52.2054,0.1132
1,1096.0,2.0,2.0,93.300000,6.5,21770.0,19888.0,11500.0,51.7548,-1.2544
2,1413.0,3.0,86.0,75.800000,6.5,17040.0,15440.0,12000.0,56.3417,-2.7943
3,1907.0,4.0,8.0,86.600000,6.5,23500.0,29900.0,10700.0,51.4988,-0.1749
4,1966.0,5.0,404.0,72.800000,5.5,16400.0,16400.0,9398.0,52.7650,-1.2321
...,...,...,...,...,...,...,...,...,...,...
126,1992.0,127.0,971.0,73.960714,4.5,10700.0,11700.0,10229.0,51.5076,0.0651
127,2006.0,128.0,1281.0,73.960714,4.5,9750.0,9900.0,9415.0,51.8779,-0.4093
128,2007.0,129.0,4030.0,73.960714,4.5,9495.0,9495.0,9415.0,52.0523,1.1629
129,2008.0,130.0,2397.0,73.960714,4.5,10250.0,10500.0,7771.0,53.0526,-3.0062
130,1962.0,131.0,2759.0,73.960714,5.5,9250.0,9250.0,10229.0,51.5017,0.0055

In [14]:
print(df.isnull().sum())

Founded_year                                     0
UK_rank                                          0
World_rank                                       0
CWUR_score                                       0
Minimum_IELTS_score                              0
UG_average_fees_(in_pounds)                      0
PG_average_fees_(in_pounds)                      0
Estimated_cost_of_living_per_year_(in_pounds)    0
Latitude                                         0
Longitude                                        0
dtype: int64